# Site settings
title: Fazani Leal Feitosa
description: Fazani Leal Feitosa
owner: vinnyfs89
url: "http://fazanileal.com.br"
image: "/images/banner.jpg"
baseurl: ""
social:
  twitter: https://twitter.com/x
  github: https://github.com/x
  facebook-official: https://www.facebook.com/groups/x/
  instagram: https://www.instagram.com/x
  email: fazani@hotmail.com.br

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
paginate: 4
paginate_path: "/blog/page:num"
